<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<?php
/**
 *THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION;LOSS OF HEALTH IN ANY FORM) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * @version 
 * @author Mehdi Fanai
 * @copyright Copyright (C) 2011 Mehdi Fanai. All rights reserved.
 * @license GNU GPLv3 <http://www.gnu.org/licenses/gpl.html>
 * @link http://www.MedAlyser.com
 */
/**
 * $this->view->serverUrl; #BaseURL (eg http://www.mydomain.com)
 *$this->view->url(); #Current path (eg. /browse/page/1 )
 */
?>
<!--<?php
$figlet = new Zend_Text_Figlet(array('outputWidth' => 95));
echo $figlet->render('MedAlyser');
?>
-->
<?php
$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 
Zend_Registry::get('globalsettings')->site->language);
$this->headMeta()->appendName('keywords', 
Zend_Registry::get('globalsettings')->site->keywords);
$this->headMeta()->appendName('description', 
Zend_Registry::get('globalsettings')->site->description);
$this->headMeta()->appendName('generator', 
'MedAlyser - Next generation EHR and clinical decision support system.');
// setting the site in the title
$this->headTitle(Zend_Registry::get('globalsettings')->site->name);
// Initialize Extjs on development ENV
if (APPLICATION_ENV == 'development') {
    $this->headScript()->prependFile('./assets/javascript/extjs/ext-debug.js');
    // Load medalyser js files
    $this->headScript()->appendFile('./app.js');
} // Initialize Extjs on production ENV
else {
    $this->headScript()->prependFile('./assets/javascript/extjs/ext.js');
    // Load minimized build of medalyser
    $this->headScript()->appendFile('./app-all.js');
}
//add notification plugin
$this->headScript()->appendFile('./app/plugins/Notification.js');
//add user set extjs theme css file
if ($this->extjstemplate == 0 or ! $this->extjstemplate) {
    $this->headLink()->prependStylesheet(
    './assets/javascript/extjs/resources/css/ext-all.css');
}
if ($this->extjstemplate == 1) {
    $this->headLink()->prependStylesheet(
    './assets/javascript/extjs/resources/css/ext-all-gray.css');
}
if ($this->extjstemplate == 2) {
    $this->headLink()->prependStylesheet(
    './assets/javascript/extjs/resources/css/ext-all-access.css');
}
//add localization support to extjs
//get current set local.
//TODO:add local support to a method in a view helper.
$locale = Zend_Registry::getInstance()->get('Zend_Translate')->getLocale();
$locale = str_split($locale, 2);
if ($locale[0] !== 'en') {
    $this->headScript()->appendFile(
    './assets/javascript/extjs/locale/ext-lang-' . $locale[0] . '.js');
}
$this->headLink(
array('rel' => 'favicon', 'href' => './assets/icons/favicon.ico'), 'PREPEND');
$this->headLink()->appendStylesheet('./assets/icons/icons.css');
// Output aggregated headMeta css & js files
echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->headScript();
?>
</head>
<body scroll="no">
<div id="x-loading-mask"
	style="width: 100%; height: 100%; background-image:url(assets/images/elements/bg.jpg);background-position:center; background-repeat:no-repeat; position: absolute; z-index: 20000; left: 0; top: 0;">&#160;</div>

<div id="x-loading-panel" style="position: absolute; left: 35%; top: 30%; border: 1px solid #9c9f9d; padding: 2px; background: #d1d8db; width: 340px; text-align: center; z-index: 20001;">
<div class="x-loading-panel-mask-indicator"
	style="border: 1px solid #c1d1d6; color: #666; background: white; padding: 10px; margin: 0; padding-left: 20px; height: 200px; text-align: left;">
<img class="x-loading-panel-logo"
	style="display: block; margin-bottom: 15px;"
	src="assets/icons/start.png" /> <img src="assets/icons/loading.gif"
	style="width: 16px; height: 16px; vertical-align: middle" />&#160; <span
	id="load-status">Initializing System ...</span>
<div style="font-size: 10px; font-weight: normal; margin-top: 15px;">Copyright
&copy; 2011 MedAlyser Project</div>
</div></div>
<script type="text/javascript">
Ext.onReady(function(){
    function removeLoadMask() {
      var loading = Ext.get('x-loading-panel');
      var mask = Ext.get('x-loading-mask');
      loading.hide();
      mask.hide();
    }
    removeLoadMask();
  });  
</script>
<noscript>
<p>You need to enable javascript to use <a
	href="http://www.medalyser.com/" title="Medicine Analyser">MedAlyser</a></p>
</noscript>

</body>
</html>