<div class="container">
<div class="span-17">

<h1>Invite a Friend to Join MedAlyser</h1>

<p>Use the following form to invite a friend to join MedAlyser. An
invitation will be sent on your behalf.</p>

<?php
$this->Errors($this->errors);
?>

<?=$this->form;?>

</div>

<div id="sidebar" class="span-7 last">

<?php
echo $this->render('_menu_profile.phtml')?>

<?php
echo $this->render('_book_ad.phtml')?>

</div>

</div>