<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<?php
/**
 *THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION;LOSS OF HEALTH IN ANY FORM) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * @version 
 * @author Mehdi Fanai
 * @copyright Copyright (C) 2011 Mehdi Fanai. All rights reserved.
 * @license GNU GPLv3 <http://www.gnu.org/licenses/gpl.html>
 * @link http://www.MedAlyser.com
 */
$this->headLink()->appendStylesheet('../css/login.css');
$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 
Zend_Registry::get('globalsettings')->site->language);
$this->headMeta()->appendName('keywords', 
Zend_Registry::get('globalsettings')->site->keywords);
$this->headMeta()->appendName('description', 
Zend_Registry::get('globalsettings')->site->description);
$this->headMeta()->appendName('generator', 
'MedAlyser - Next generation EHR and clinical decision support system.');
// setting the site in the title
$this->headTitle(
Zend_Registry::get('globalsettings')->site->name . " - Sign in");
//display data
echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->headScript();
?>

</head>
<body style='min-height: 380px'>
<div class='layout' id='page'>
<div class='centered'>
<div class='column' style='margin-top: -174px'>
<div class='logo'></div>
<div class='login_page preserve_links'>
<div class='title_graphic'></div>
<div class='login_frame flexible'>
<div class='top'></div>
<div class='middle'>
<div class='flash_message'>
<div class='flash_boxes'></div>

</div>
<?php
$this->Errors($this->errors);
$this->Errors($this->authError);
?>

<?php
echo $this->form;
?>
<noscript>
<p>You need to enable javascript to use <a
	href="http://www.medalyser.com/" title="Medicine Analyser">MedAlyser</a></p>
</noscript>

</body>