<h3>Create a MedaLyser Account</h3>

<div class="login-features abs-position">
<p>The Next generation innovative open source EHR solution</p>
<p align="justify">Equipped with modern technology AJAX and Rich
Internet Applications (RIA) Framework ExtJS, medalyser offer significant
usability improvements and make interacting with the web interfaces
faster and more efficient.</p>
</div>
<?php
echo $this->form;
?>
