<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
</head>
<body>
<h3>Create a MedaLyser Account</h3>

<div class="login-features abs-position">
<p>The Next generation innovative open source EHR solution</p>
<p align="justify">Equipped with modern technology AJAX and Rich
Internet Applications (RIA) Framework ExtJS, medalyser offer significant
usability improvements and make interacting with the web interfaces
faster and more efficient.</p>
</div>
<?php
$this->Errors($this->errors);
?>
<?php

echo $this->form;
?>
</body>
</html>