<form id="login" class="onboard_form"
	action="<?=$this->element->getAction();?>"
	method="<?=$this->element->getMethod();?>">
<div style="margin: 0; padding: 0"><?=$this->element->amoodyhacker;?></div>
<div class='field text_field'><label for="email">Email address</label></div>
<div class='another_row'><?=$this->element->primaryemail;?></div>
<div class='field text_field'><label for="password">Password</label> <span>
&nbsp;&nbsp; </span> <a
	href="<?=$this->url(array('controller' => 'account', 'action' => 'lost'));?>">Forgot
password?</a></div>
<div class='one_more_row'><?=$this->element->pswd;?></div>
<div class='remember_me_field'>
<div class='field check_box_field'><?=$this->element->public;?>
<label for="remember_me" style="display: inline">Stay signed in</label>
</div>
</div>
<div class='actions'>
<div class="right masubmit"
	onclick="document.getElementById(&quot;loading_spinner&quot;).style.display = &quot;inline&quot;;">
<?=$this->element->submit;?><span></span></div>
<img alt="Sm_loader" class="right" id="loading_spinner"
	src="../icons/loading.gif" style="margin-top: 13px; display: none;" />
<div class="clear"></div>
</div>
<br />
<a
	href="<?=$this->url(array('controller' => 'account', 'action' => 'register'));?>">Create
account</a> <br />
<div class="clear"></div>
</form>
