<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * AdminprofileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminprofileRepository extends EntityRepository
{
}