<?php
namespace Repositories;
use Doctrine\ORM\EntityRepository;
/**
 * AdminprofileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminprofileRepository extends EntityRepository
{
    //find a user by id and return as array
    public function findByUserid ($param)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->add('select', 'a')
            ->add('from', 'Entities\Adminprofile a')
            ->add('where', 'a.userid = :userid')
            ->setParameter('userid', $param);
        return $qb->getQuery()->getResult(2);
    }
}