<?php
namespace Repositories;
use Doctrine\ORM\EntityRepository;
/**
 * AdminaddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminaddressRepository extends EntityRepository
{
}