<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * InsurancecompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsurancecompanyRepository extends EntityRepository
{
}