<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PatientprofileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientprofileRepository extends EntityRepository
{
}