<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PatientschoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientschoolRepository extends EntityRepository
{
}