<?php
namespace Repositories;
use Doctrine\ORM\EntityRepository;
/**
 * PatientcontactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientcontactRepository extends EntityRepository
{
}