<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PatientaddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientaddressRepository extends EntityRepository
{
}